__include__: [
  '../dfine/dfine_hgnetv2_n_custom.yml',
  '../dataset/user_detection.yml',
  '../base/deim.yml'
]

print_freq: 50
output_dir: ./outputs/deim_hgnetv2_n_custom

model: DEIM_MG

DEIM_MG:
  yaml_path: configs/cfg/dfine-n.yaml
  pretrained: D:/YOLO/DEIM/DEIM_20251224/DEIM/weight/hgnetv2/deim_dfine_hgnetv2_n_coco_160e_MG.pth
optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0004
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0004
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0008
  betas: [0.9, 0.999]
  weight_decay: 0.0001
  # type: SGD
  # params:
  #   - params: '^(?=.*backbone)(?!.*norm|bn).*$'
  #     lr: 0.001
  #   - params: '^(?=.*backbone)(?=.*norm|bn).*$'
  #     lr: 0.001
  #     weight_decay: 0.
  #   - params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
  #     weight_decay: 0.

  # lr: 0.01
  # momentum: 0.9
  # weight_decay: 0.0005
  # nesterov: True

# Increase to search for the optimal ema
epoches: 400 # 148 + 12

## Our LR-Scheduler
flat_epoch: 194    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 20
lr_gamma: 0.8
checkpoint_freq: 50    # save freq
## Our DataAug
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 194, 380]   # list

  total_batch_size: 8  # total batch size equals to 16 (4 * 4)

  collate_fn:
    mixup_prob: 0.4
    mixup_epochs: [4, 194]
    stop_epoch: 380
    base_size_repeat: ~

val_dataloader:
  total_batch_size: 8