# https://pan.baidu.com/s/1fqFUNErDxQN7rFuWaoqH2g?pwd=y1hu

task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', 'segm']

num_classes: 4 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/YOLO/DEIM/DEIM_20251224/DEIM/dataset/YOLO_Format1/images/train
    ann_file: D:/YOLO/DEIM/DEIM_20251224/DEIM/dataset/YOLO_Format1/annotations/train.json
    return_masks: True
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 0
  drop_last: True
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:/YOLO/DEIM/DEIM_20251224/DEIM/dataset/YOLO_Format1/images/val
    ann_file: D:/YOLO/DEIM/DEIM_20251224/DEIM/dataset/YOLO_Format1/annotations/val.json
    return_masks: True
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 0
  drop_last: False
  pin_memory: True
  collate_fn:
    type: BatchImageCollateFunction