__include__: [
  # '../dataset/custom_detection.yml',
  'car_seg.yml',
  '../runtime_seg.yml',
  '../base/dataloader_dfine.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
  '../base/deim.yml',
]

print_freq: 50
output_dir: ./outputs_Seg/dfine_hgnetv2_n_custom
eval_mask_ratio: 4 #验证集4倍下采样
postprocessor: SegPostProcessor #后处理器
model: DEIM_MG

DEIM_MG:
  yaml_path: D:/YOLO/DEIM/DEIM_20251224/DEIM/configs/cfg/define-n-seg.yaml
  pretrained: D:/YOLO/DEIM/DEIM_20251224/DEIM/weight/hgnetv2/PPHGNetV2_B0_stage1_MG.pth
  
DEIM:
  backbone: HGNetv2
  decoder: DFINESegTransformer
  
optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0004
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0004
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0008
  betas: [0.9, 0.999]
  weight_decay: 0.0001

DEIMCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5,loss_mask_ps_ce: 10.0,loss_mask_ps_dice: 5.0}
  losses: ['vfl', 'boxes', 'local','mask_ps']
  alpha: 0.75
  gamma: 2.0
  reg_max: 32
# Increase to search for the optimal ema
# Increase to search for the optimal ema
epoches: 400 # 148 + 12

## Our LR-Scheduler
flat_epoch: 194    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 20
lr_gamma: 0.8
checkpoint_freq: 50    # save freq
## Our DataAug
train_dataloader: 
  num_workers: 0
  dataset: 
    transforms:
      policy:
        epoch: [4, 194, 380]   # list

  total_batch_size: 8  # total batch size equals to 16 (4 * 4)

  collate_fn:
    mixup_prob: 0.4
    mixup_epochs: [4, 194]
    stop_epoch: 380
    base_size_repeat: ~

val_dataloader: 
  num_workers: 0
  total_batch_size: 4


  
